-- ============================================================================
-- REFERENCIA (no ejecutar): esquema actual de public.torrents en Supabase.
-- El script de mantenimiento está adaptado a estas columnas, tipos y CHECKs.
-- Depende de las funciones torrent_title_key() y torrent_effective_title(), que
-- ya existen en tu proyecto. La última sentencia llegó truncada; se completa
-- asumiendo que es el trigger duplicado (ver 002_preserve_updated_at.sql).
-- ============================================================================

create table public.torrents (
  id bigint generated by default as identity not null,
  imdb_id text null,
  tmdb_id bigint null,
  kitsu_id bigint null,
  anilist_id bigint null,
  mal_id bigint null,
  type character varying(10) not null default 'movie'::character varying,
  season integer null,
  episode integer null,
  absolute_episode integer null,
  file_index integer null,
  info_hash character varying(40) not null,
  info_hash_clean character varying GENERATED ALWAYS as (lower((info_hash)::text)) STORED (40) null,
  title text not null,
  release_group character varying(100) null,
  quality character varying(20) not null default 'Unknown'::character varying,
  codec character varying(20) null,
  hdr_format character varying(20) null,
  audio text[] not null default '{}'::text[],
  subtitles text[] not null default '{}'::text[],
  channels character varying(10) null,
  size_bytes bigint not null default 0,
  seeders integer not null default 0,
  leechers integer not null default 0,
  source_tracker character varying(100) null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  title_text text null,
  hdr text null,
  ids_checked_at timestamp with time zone null,
  ids_source text null,
  ids_confidence double precision null,
  ids_attempts integer null default 0,
  constraint torrents_pkey primary key (id),
  constraint torrents_episode_valid check (((episode is null) or (episode >= 0))),
  constraint torrents_file_index_valid check (((file_index is null) or (file_index >= 0))),
  constraint torrents_imdb_format check (((imdb_id is null) or (imdb_id ~ '^tt[0-9]+$'::text))),
  constraint torrents_info_hash_format check (((info_hash)::text ~ '^[a-fA-F0-9]{40}$'::text)),
  constraint torrents_leechers_valid check ((leechers >= 0)),
  constraint torrents_season_valid check (((season is null) or (season >= 0))),
  constraint torrents_seeders_valid check ((seeders >= 0)),
  constraint torrents_size_valid check ((size_bytes >= 0)),
  constraint torrents_absolute_episode_valid check (((absolute_episode is null) or (absolute_episode >= 0))),
  constraint torrents_type_valid check (((type)::text = any ((array['movie'::character varying, 'series'::character varying, 'anime'::character varying])::text[])))
) TABLESPACE pg_default;

create unique index if not exists idx_torrents_unique_hash on public.torrents using btree (info_hash_clean);
create index if not exists idx_torrents_stremio_imdb on public.torrents using btree (imdb_id, season, episode, seeders desc) where (imdb_id is not null);
create index if not exists idx_torrents_tmdb on public.torrents using btree (tmdb_id, season, episode, seeders desc) where (tmdb_id is not null);
create index if not exists idx_torrents_kitsu on public.torrents using btree (kitsu_id, episode, absolute_episode, seeders desc) where (kitsu_id is not null);
create index if not exists idx_torrents_anilist on public.torrents using btree (anilist_id, episode, absolute_episode, seeders desc) where (anilist_id is not null);
create index if not exists idx_torrents_mal on public.torrents using btree (mal_id, episode, absolute_episode, seeders desc) where (mal_id is not null);
create index if not exists idx_torrents_active on public.torrents using btree (imdb_id, seeders desc) where (seeders > 0);
create index if not exists torrents_ids_checked_at_idx on public.torrents using btree (ids_checked_at);
create index if not exists torrents_tmdb_idx on public.torrents using btree (tmdb_id);
create index if not exists torrents_imdb_idx on public.torrents using btree (imdb_id);
create index if not exists torrents_anilist_idx on public.torrents using btree (anilist_id);
create index if not exists torrents_kitsu_idx on public.torrents using btree (kitsu_id);
create index if not exists torrents_mal_idx on public.torrents using btree (mal_id);
create index if not exists torrents_type_idx on public.torrents using btree (type);
create index if not exists torrents_title_key_idx on public.torrents using btree (torrent_title_key (torrent_effective_title (title, title_text)));

create trigger trg_torrents_updated_at before update on torrents
  for each row execute function update_torrents_updated_at ();
create trigger update_torrents_updated_at before update on torrents
  for each row execute function update_torrents_updated_at ();
